### ISSUE TITLE
Mining Mechanism

### ISSUE THREAD

**Issue by SourenP** [SourenP/ungroup_game#14]

**Comment by copacetic** [comment]
An event triggered in the physics controller on collision will contain the GameObject IDs of the two collided objects. Could be Mine/Group, Group/Group, or even Mine/Mine (impossible since mines dont move)

This event will be handled in GameController. LevelController we realized is really meant to be a queryable store, not a "controller."We will likely split up GameController later as well.

The handling of the event will rely on the ID in the objects. If the ID is within 0-100,000 range, then we'll assume it's a Group, 100,000-200,000 Mine, 300,000 - 400,000 Player. These ranges are idiotically broad and should never lead to collisions. However, in our creation code we should check the ranges otherwise we may run into collisions (imagine Group with ID 100,001 and Mine with ID 100,001 colliding, it would start to get confusing.

Once we know the object type, essentially mod the "base value" (100k, 200k, 300k...) to get to an "index value" we use to do lookups in the storing arrays. 

Once we have the two objects looked up, if it's a Group <-> Mine collision, we decide how much mine value to transfer from the mine to the group. Once the transfer is done, we end processing of that collision event.

**Comment by SourenP** [comment]
FYI renamed `LevelController` to `GameObjectStore` in https://github.com/ungroup/ungroup_game/pull/80
